//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAK5
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationHistory
    {
        public int HistoryID { get; set; }
        public string OperationType { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Description { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
